# Generated by Django 4.2 on 2023-04-07 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_name',
            new_name='Nombre_de_la_tarea',
        ),
    ]
