# Generated by Django 4.2 on 2023-04-07 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_due_date_task_fecha_de_vencimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='completed',
            new_name='completado',
        ),
    ]
